{{ $featureGates := .Values.featureGates }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
{{- end }}

{{ if $featureGates.MongoDB }}

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '3.6.13-v1'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "mongo") $) }}:3.6.13'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb-init") $) }}:4.1-v2'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-3.6.13
      restoreTask:
        name: mongodb-restore-3.6.13
  version: 3.6.13

---
{{ if or (not .Values.skipDeprecated) (has "3.6-v4" .Values.enableVersions.MongoDB) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '3.6-v4'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongo") $) }}:3.6-v4'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/busybox") $) }}'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  version: 3.6.13
  deprecated: {{ not (has "3.6-v4" .Values.enableVersions.MongoDB) }}
{{ end }}

---
{{ if or (not .Values.skipDeprecated) (has "3.6-v5" .Values.enableVersions.MongoDB) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '3.6-v5'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongo") $) }}:3.6-v5'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb-init") $) }}:0.1.0'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  version: 3.6.13
  deprecated: {{ not (has "3.6-v5" .Values.enableVersions.MongoDB) }}
{{ end }}

---
{{ if or (not .Values.skipDeprecated) (has "3.6.13" .Values.enableVersions.MongoDB) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '3.6.13'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongo") $) }}:3.6.13'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/busybox") $) }}'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  version: 3.6.13
  deprecated: {{ not (has "3.6.13" .Values.enableVersions.MongoDB) }}
{{ end }}
{{ end }}
