{{ $featureGates := .Values.featureGates }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
{{- end }}

{{ if $featureGates.MongoDB }}

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 'percona-3.6.18'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "percona/percona-server-mongodb") $) }}:3.6.18'
  distribution: Percona
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb-init") $) }}:4.1-v2'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-3.6.13
      restoreTask:
        name: mongodb-restore-3.6.13
  version: 3.6.18
{{ end }}
