{{ $featureGates := .Values.featureGates }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
{{- end }}

{{ if $featureGates.MongoDB }}

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '4.0.3-v1'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "mongo") $) }}:4.0.3'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb-init") $) }}:4.1-v2'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-4.0.3
      restoreTask:
        name: mongodb-restore-4.0.3
  version: 4.0.3

---
{{ if or (not .Values.skipDeprecated) (has "4.0.3" .Values.enableVersions.MongoDB) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: '4.0.3'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongo") $) }}:4.0.3'
  distribution: Official
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/busybox") $) }}'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  version: 4.0.3
  deprecated: {{ not (has "4.0.3" .Values.enableVersions.MongoDB) }}
{{ end }}
{{ end }}
