{{ $featureGates := .Values.featureGates }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
{{- end }}

{{ if $featureGates.MongoDB }}

apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  name: 'percona-4.4.10'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  db:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "percona/percona-server-mongodb") $) }}:4.4.10'
  distribution: Percona
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/mongodb_exporter") $) }}:v0.20.4'
  initContainer:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "ak8sdb/mongodb-init") $) }}:4.2-v6'
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/replication-mode-detector") $) }}:v0.11.0'
  stash:
    addon:
      backupTask:
        name: mongodb-backup-4.4.6
      restoreTask:
        name: mongodb-restore-4.4.6
  version: 4.4.10
{{ end }}
