{{ $featureGates := .Values.featureGates }}
{{- if .Values.global }}
  {{ $featureGates = mergeOverwrite dict .Values.featureGates .Values.global.featureGates }}
{{- end }}

{{ if $featureGates.Elasticsearch }}

apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: 'xpack-6.8.10-v1'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  authPlugin: X-Pack
  db:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "elasticsearch") $) }}:6.8.10'
  distribution: ElasticStack
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "prometheuscommunity/elasticsearch-exporter") $) }}:v1.3.0'
  initContainer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "tianon/toybox") $) }}:0.8.4'
    yqImage: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/elasticsearch-init") $) }}:6.8.10-xpack-v1'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-6.8.0
      restoreTask:
        name: elasticsearch-restore-6.8.0
  version: 6.8.10

---
{{ if or (not .Values.skipDeprecated) (has "xpack-6.8.10" .Values.enableVersions.Elasticsearch) }}
apiVersion: catalog.kubedb.com/v1alpha1
kind: ElasticsearchVersion
metadata:
  name: 'xpack-6.8.10'
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  authPlugin: X-Pack
  db:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "elasticsearch") $) }}:6.8.10'
  distribution: ElasticStack
  exporter:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "prometheuscommunity/elasticsearch-exporter") $) }}:v1.3.0'
  initContainer:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "busybox") $) }}:1.32.0'
    yqImage: '{{ include "image.dockerHub" (merge (dict "_repo" "kubedb/elasticsearch-init") $) }}:6.8.10-xpack'
  podSecurityPolicies:
    databasePolicyName: elasticsearch-db
  stash:
    addon:
      backupTask:
        name: elasticsearch-backup-6.8.0
      restoreTask:
        name: elasticsearch-restore-6.8.0
  version: 6.8.10
  deprecated: {{ not (has "xpack-6.8.10" .Values.enableVersions.Elasticsearch) }}
{{ end }}
{{ end }}
