project:
  name: KubeDB Catalog
  shortName: KubeDB Catalog
  url: https://github.com/kubedb
  description: Catalog of database versions supported by KubeDB
  app: KubeDB catalog
repository:
  url: https://raw.githubusercontent.com/ak8sdb/installer/master/stable
  name: ak8sdb
chart:
  name: kubedb-catalog
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.14+
release:
  name: kubedb-catalog
  namespace: kubedb
