# Default values for kubedb-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

# Docker registry fqdn used to pull KubeDB related images
# Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
registryFQDN: ""

image:
  # Docker registry used to pull database image
  registry: ""

  # If true, uses image registry for pulling official docker images.
  # This can be used to pull images from a private registry
  overrideOfficialRegistry: false

catalog:
  # If true, deploys Elasticsearch version catalog
  elasticsearch: true
  # If true, deploys MongoDB version catalog
  mongodb: true

psp:
  elasticsearch:
    allowPrivilegeEscalation: true
    privileged: true
  mongodb:
    allowPrivilegeEscalation: false
    privileged: false

# Set true to avoid deploying deprecated versions
skipDeprecated: true
