# Default values for kubedb-catalog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

proxies:
  dockerHub: ""
  dockerLibrary: ""
  ghcr: ghcr.io
  kubernetes: registry.k8s.io

featureGates:
  Elasticsearch: true
  MongoDB: true

psp:
  enabled: false
  elasticsearch:
    allowPrivilegeEscalation: true
    privileged: true
  mongodb:
    allowPrivilegeEscalation: false
    privileged: false

# Set true to avoid deploying deprecated versions
skipDeprecated: true

enableVersions:
  Elasticsearch: []
  MongoDB: []
