apiVersion: v1
description: KubeDB Autoscaler by AppsCode - Autoscale KubeDB operated Databases
name: kubedb-autoscaler
version: v2025.9.26
appVersion: v2025.9.26
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-autoscaler-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
