apiVersion: v1
description: KubeDB Enterprise by AppsCode - Enterprise features for KubeDB
name: kubedb-enterprise
version: v2022.03.30
appVersion: v2022.03.30
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-enterprise-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
