apiVersion: v2
name: kubedb
description: 'KubeDB by AppsCode - Production ready databases on Kubernetes'
type: application
version: v0.1.0
appVersion: v0.1.0
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: kubedb-crds
  version: v0.16.2
  repository: file://../kubedb-crds
  condition: kubedb-crds.enabled
- name: kubedb-community
  version: v0.16.2
  repository: https://charts.appscode.com/stable
  condition: kubedb-community.enabled
- name: kubedb-catalog
  version: v0.16.2
  repository: https://charts.appscode.com/stable
  condition: kubedb-catalog.enabled
- name: kubedb-enterprise
  version: v0.3.2
  repository: https://charts.appscode.com/stable
  condition: kubedb-enterprise.enabled
- name: kubedb-autoscaler
  version: v0.1.2
  repository: https://charts.appscode.com/stable
  condition: kubedb-autoscaler.enabled
- name: stash-community
  version: v0.11.9
  repository: https://charts.appscode.com/stable
  condition: stash-community.enabled
- name: stash-mongodb
  version: 4.0.11-v5
  repository: https://charts.appscode.com/stable
  condition: stash-mongodb.enabled
- name: stash-elasticsearch
  version: 7.3.2-v6
  repository: https://charts.appscode.com/stable
  condition: stash-elasticsearch.enabled
