apiVersion: v2
name: kubedb
description: 'KubeDB by AppsCode - Production ready databases on Kubernetes'
type: application
version: v2021.09.09
appVersion: v2021.09.09
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: kubedb-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.09.09
  condition: kubedb-catalog.enabled
- name: kubedb-community
  repository: https://charts.appscode.com/stable/
  version: v0.21.0
  condition: kubedb-community.enabled
- name: kubedb-enterprise
  repository: https://charts.appscode.com/stable/
  version: v0.8.0
  condition: kubedb-enterprise.enabled
- name: kubedb-autoscaler
  repository: https://charts.appscode.com/stable/
  version: v0.6.0
  condition: kubedb-autoscaler.enabled
- name: stash-community
  repository: https://charts.appscode.com/stable/
  version: v0.14.1
  condition: stash-community.enabled
- name: stash-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.06.23
  condition: stash-catalog.enabled
