apiVersion: v2
name: kubedb
description: 'KubeDB by AppsCode - Production ready databases on Kubernetes'
type: application
version: v2021.04.16
appVersion: v2021.04.16
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: kubedb-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.04.16
  condition: kubedb-catalog.enabled
- name: kubedb-community
  repository: https://charts.appscode.com/stable/
  version: v0.18.0
  condition: kubedb-community.enabled
- name: kubedb-enterprise
  repository: https://charts.appscode.com/stable/
  version: v0.5.0
  condition: kubedb-enterprise.enabled
- name: kubedb-autoscaler
  repository: https://charts.appscode.com/stable/
  version: v0.3.0
  condition: kubedb-autoscaler.enabled
- name: stash-community
  repository: https://charts.appscode.com/stable/
  version: v0.12.3
  condition: stash-community.enabled
- name: stash-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.04.12
  condition: stash-catalog.enabled
