apiVersion: v2
name: kubedb
description: KubeDB by AppsCode - Production ready databases on Kubernetes
type: application
version: v2022.02.22
appVersion: v2022.02.22
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: kubedb-catalog
  repository: file://../kubedb-catalog
  version: v2022.02.22
  condition: kubedb-catalog.enabled
- name: kubedb-community
  repository: file://../kubedb-community
  version: v2022.02.22
  condition: kubedb-community.enabled
- name: kubedb-enterprise
  repository: file://../kubedb-enterprise
  version: v2022.02.22
  condition: kubedb-enterprise.enabled
- name: kubedb-autoscaler
  repository: file://../kubedb-autoscaler
  version: v2022.02.22
  condition: kubedb-autoscaler.enabled
- name: stash-community
  repository: https://charts.appscode.com/stable/
  version: v0.17.0
  condition: stash-community.enabled
- name: stash-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.11.24
  condition: stash-catalog.enabled
