# Default values for kubedb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # License for the product.
  # Get a license by following the steps from [here](https://kubedb.com/docs/latest/setup/install/enterprise#get-a-trial-license).
  # Example:
  # helm install appscode/kubedb \
  #   --set-file global.license=/path/to/license/file
  # or
  # helm install appscode/kubedb \
  #   --set global.license=<license file content>
  license: ""

  # Docker registry used to pull KubeDB related images
  registry: ""

  # Docker registry fqdn used to pull KubeDB related images.
  # Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
  registryFQDN: ""

  # Specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  #
  # Example:
  # helm template charts/kubedb \
  #   --set global.imagePullSecrets[0].name=sec0 \
  #   --set global.imagePullSecrets[1].name=sec1
  imagePullSecrets: []

  # Skip generating cleaner job YAML
  skipCleaner: false

  monitoring:
    # If true, enables monitoring KubeDB operator
    enabled: false
    # Name of monitoring agent ("prometheus.io" or "prometheus.io/operator" or "prometheus.io/builtin")
    agent: ""
    serviceMonitor:
      # Specify the labels for ServiceMonitor.
      # Prometheus crd will select ServiceMonitor using these labels.
      # Only usable when monitoring agent is `prometheus.io/operator`.
      labels: {}

kubedb-catalog:
  # If enabled, installs the kubedb-catalog chart
  enabled: true
  catalog:
    elasticsearch: true
    etcd: false
    memcached: false
    mongo: true
    mysql: false
    mariadb: false
    perconaxtradb: false
    pgbouncer: false
    postgres: false
    proxysql: false
    redis: false
kubedb-community:
  # If enabled, installs the kubedb-community chart
  enabled: true
  operator:
    # Docker registry used to pull KubeDB enterprise operator image
    registry: ghcr.io/ak8sdb
    # KubeDB enterprise operator container image tag
    tag: v2021.06.23
kubedb-enterprise:
  # If enabled, installs the kubedb-enterprise chart
  enabled: true
  operator:
    # Docker registry used to pull KubeDB enterprise operator image
    registry: ghcr.io/ak8sdb
    # KubeDB enterprise operator container image tag
    tag: v2021.06.23
kubedb-autoscaler:
  # If enabled, installs the kubedb-autoscaler chart
  enabled: true
  operator:
    # Docker registry used to pull KubeDB enterprise operator image
    registry: ghcr.io/ak8sdb
    # KubeDB enterprise operator container image tag
    tag: v2021.06.23

stash-community:
  # If enabled, installs the stash-community chart
  enabled: true
  operator:
    # Docker registry used to pull operator image
    registry: ghcr.io/ak8sdb
    # Operator container image tag
    tag: v2021.06.23

stash-catalog:
  # If enabled, installs the stash-catalog chart
  enabled: true
  elasticsearch:
    # If true, deploys Elasticsearch addon
    enabled: true
  mariadb:
    # If true, deploys MariaDB addon
    enabled: false
  mongodb:
    # If true, deploys MongoDB addon
    enabled: true
  mysql:
    # If true, deploys MySQL addon
    enabled: false
  perconaxtradb:
    # If true, deploys Percona XtraDB addon
    enabled: false
  postgres:
    # If true, deploys PostgreSQL addon
    enabled: false
